name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [native, context, swoole-concurrent, open-swoole-concurrent]

    name: Runtime - ${{ matrix.runtime }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, swoole, openswoole
          coverage: none

      - name: Run Integration Test
        working-directory: tests/Integration/runtimes/${{ matrix.runtime }}
        run: |
          chmod +x test.sh
          ./test.sh
