name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.5']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run rector
        run: composer rector
      - name: Run pint
        run: composer lint
      - name: composer validate
        run: composer install --no-interaction --prefer-dist       
      - name: Run tests
        run: composer test

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [native, context, swoole-concurrent, open-swoole-concurrent]
        php: ['8.4', '8.5']
        exclude:
          - runtime: swoole-concurrent
            php: '8.5'
          - runtime: open-swoole-concurrent
            php: '8.5'

    name: ${{ matrix.runtime }} (PHP ${{ matrix.php }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # Swoole and OpenSwoole cannot be loaded at the same time as they share function names.
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, ${{ matrix.runtime == 'open-swoole-concurrent' && 'openswoole' || 'swoole' }}
          coverage: none

      - name: Run Integration Test
        working-directory: tests/Integration/runtimes/${{ matrix.runtime }}
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: |
          chmod +x test.sh
          ./test.sh

